version: '3'
services:
  client:
    build:
      context: ./client
    restart: "always"
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      server:
        condition: service_started
    networks:
      - ir-network

  server:
    build:
      context: ./server
    restart: always
    ports:
      - "5000:5000"
    container_name: server
    depends_on:
      - db
    links:
      - db
    networks:
      - ir-network
  
  db:
    image: mongo:6
    container_name: db
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ir-network 

volumes: 
  db:

networks:
  ir-network:
    name: 'ir-network'
    driver: bridge


